CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('ADMIN', 'CUSTOMER')),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE city (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL UNIQUE,
    timezone VARCHAR(60) NOT NULL
);

CREATE TABLE theater (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_id BIGINT NOT NULL REFERENCES city(id),
    name VARCHAR(160) NOT NULL,
    address VARCHAR(500) NOT NULL,
    UNIQUE (city_id, name)
);

CREATE TABLE screen (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    theater_id BIGINT NOT NULL REFERENCES theater(id),
    name VARCHAR(80) NOT NULL,
    UNIQUE (theater_id, name)
);

CREATE TABLE seat (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    screen_id BIGINT NOT NULL REFERENCES screen(id),
    row_label VARCHAR(10) NOT NULL,
    seat_number INTEGER NOT NULL CHECK (seat_number > 0),
    category VARCHAR(20) NOT NULL CHECK (category IN ('REGULAR', 'PREMIUM')),
    UNIQUE (screen_id, row_label, seat_number)
);

CREATE TABLE movie (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    duration_minutes INTEGER NOT NULL CHECK (duration_minutes > 0),
    certificate VARCHAR(20),
    language VARCHAR(60) NOT NULL
);

CREATE TABLE pricing_tier (
    category VARCHAR(20) PRIMARY KEY CHECK (category IN ('REGULAR', 'PREMIUM')),
    multiplier_bps INTEGER NOT NULL CHECK (multiplier_bps > 0)
);

CREATE TABLE refund_policy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL UNIQUE
);

CREATE TABLE refund_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_id BIGINT NOT NULL REFERENCES refund_policy(id) ON DELETE CASCADE,
    minimum_minutes_before BIGINT NOT NULL CHECK (minimum_minutes_before >= 0),
    refund_percent INTEGER NOT NULL CHECK (refund_percent BETWEEN 0 AND 100),
    UNIQUE (policy_id, minimum_minutes_before)
);

CREATE TABLE showing (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id BIGINT NOT NULL REFERENCES movie(id),
    screen_id BIGINT NOT NULL REFERENCES screen(id),
    refund_policy_id BIGINT NOT NULL REFERENCES refund_policy(id),
    starts_at TIMESTAMP WITH TIME ZONE NOT NULL,
    base_price_cents BIGINT NOT NULL CHECK (base_price_cents > 0),
    weekend_multiplier_bps INTEGER NOT NULL DEFAULT 10000 CHECK (weekend_multiplier_bps > 0),
    status VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED' CHECK (status IN ('SCHEDULED', 'CANCELLED'))
);

CREATE INDEX idx_showing_movie_start ON showing(movie_id, starts_at);
CREATE INDEX idx_showing_screen_start ON showing(screen_id, starts_at);

CREATE TABLE show_seat (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    showing_id BIGINT NOT NULL REFERENCES showing(id),
    seat_id BIGINT NOT NULL REFERENCES seat(id),
    category VARCHAR(20) NOT NULL,
    price_cents BIGINT NOT NULL CHECK (price_cents > 0),
    status VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE' CHECK (status IN ('AVAILABLE', 'HELD', 'BOOKED')),
    hold_id VARCHAR(36),
    hold_expires_at TIMESTAMP WITH TIME ZONE,
    booking_id VARCHAR(36),
    version BIGINT NOT NULL DEFAULT 0,
    UNIQUE (showing_id, seat_id)
);

CREATE INDEX idx_show_seat_showing_status ON show_seat(showing_id, status);
CREATE INDEX idx_show_seat_hold ON show_seat(hold_id);

CREATE TABLE discount_code (
    code VARCHAR(40) PRIMARY KEY,
    kind VARCHAR(20) NOT NULL CHECK (kind IN ('PERCENT', 'FIXED')),
    value_amount BIGINT NOT NULL CHECK (value_amount > 0),
    minimum_order_cents BIGINT NOT NULL DEFAULT 0,
    valid_from TIMESTAMP WITH TIME ZONE NOT NULL,
    valid_until TIMESTAMP WITH TIME ZONE NOT NULL,
    max_redemptions INTEGER,
    redemption_count INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CHECK (valid_until > valid_from),
    CHECK (max_redemptions IS NULL OR max_redemptions > 0)
);

CREATE TABLE seat_hold (
    id VARCHAR(36) PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES app_user(id),
    showing_id BIGINT NOT NULL REFERENCES showing(id),
    status VARCHAR(20) NOT NULL CHECK (status IN ('ACTIVE', 'EXPIRED', 'CONVERTED')),
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE seat_hold_item (
    hold_id VARCHAR(36) NOT NULL REFERENCES seat_hold(id),
    show_seat_id BIGINT NOT NULL REFERENCES show_seat(id),
    price_cents BIGINT NOT NULL,
    PRIMARY KEY (hold_id, show_seat_id)
);

CREATE TABLE booking (
    id VARCHAR(36) PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES app_user(id),
    showing_id BIGINT NOT NULL REFERENCES showing(id),
    hold_id VARCHAR(36) NOT NULL UNIQUE REFERENCES seat_hold(id),
    idempotency_key VARCHAR(80) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('CONFIRMED', 'CANCELLED')),
    subtotal_cents BIGINT NOT NULL,
    discount_cents BIGINT NOT NULL,
    total_cents BIGINT NOT NULL,
    currency VARCHAR(3) NOT NULL,
    discount_code VARCHAR(40),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    cancelled_at TIMESTAMP WITH TIME ZONE,
    UNIQUE (customer_id, idempotency_key)
);

CREATE INDEX idx_booking_customer_created ON booking(customer_id, created_at);

CREATE TABLE booking_item (
    booking_id VARCHAR(36) NOT NULL REFERENCES booking(id),
    show_seat_id BIGINT NOT NULL REFERENCES show_seat(id),
    seat_label VARCHAR(30) NOT NULL,
    price_cents BIGINT NOT NULL,
    PRIMARY KEY (booking_id, show_seat_id)
);

CREATE TABLE payment (
    id VARCHAR(36) PRIMARY KEY,
    booking_id VARCHAR(36) NOT NULL UNIQUE REFERENCES booking(id),
    amount_cents BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('CAPTURED', 'REFUNDED')),
    provider_reference VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE refund (
    id VARCHAR(36) PRIMARY KEY,
    booking_id VARCHAR(36) NOT NULL UNIQUE REFERENCES booking(id),
    amount_cents BIGINT NOT NULL,
    refund_percent INTEGER NOT NULL,
    provider_reference VARCHAR(100),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE outbox_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_id VARCHAR(80) NOT NULL,
    event_type VARCHAR(80) NOT NULL,
    payload TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'SENT', 'FAILED')),
    attempts INTEGER NOT NULL DEFAULT 0,
    available_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    sent_at TIMESTAMP WITH TIME ZONE,
    dedupe_key VARCHAR(160) NOT NULL UNIQUE
);

CREATE INDEX idx_outbox_pending ON outbox_event(status, available_at);

INSERT INTO pricing_tier(category, multiplier_bps) VALUES ('REGULAR', 10000);
INSERT INTO pricing_tier(category, multiplier_bps) VALUES ('PREMIUM', 15000);

